// Generated by openapi-typescript 7.13.0. Do not edit.
export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process health */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Database/schema readiness independent of AI */
        get: operations["get_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Initialization and current authentication status */
        get: operations["get_auth_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mcp/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue enrolled-key challenge */
        post: operations["post_auth_mcp_challenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mcp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify key proof and issue session */
        post: operations["post_auth_mcp_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/credentials/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue authenticated enrollment challenge */
        post: operations["post_auth_credentials_challenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/credentials/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify and enroll credential */
        post: operations["post_auth_credentials_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Passkey register options
         * @description Registration requires an authenticated owner or a valid one-use administrator setup/recovery token; authentication options are public. Requests require matching browser origin.
         */
        post: operations["post_auth_register_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Passkey register verification
         * @description Sets the browser session cookie on success. Registration without setupToken requires existing authentication.
         */
        post: operations["post_auth_register_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Passkey login options
         * @description Registration requires an authenticated owner or a valid one-use administrator setup/recovery token; authentication options are public. Requests require matching browser origin.
         */
        post: operations["post_auth_login_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Passkey login verification
         * @description Sets the browser session cookie on success. Registration without setupToken requires existing authentication.
         */
        post: operations["post_auth_login_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke current session and clear cookie */
        post: operations["post_auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List public credential metadata */
        get: operations["get_auth_credentials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/credentials/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke credential and associated sessions */
        delete: operations["delete_auth_credentials_id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owner presentation and selected database engine */
        get: operations["get_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update owner presentation */
        patch: operations["patch_profile"];
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects and source identities */
        get: operations["get_projects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve normalized Git remote identity */
        post: operations["post_projects_resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/resolve-explicit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve owner-confirmed project or create non-Git project
         * @description Supply projectId to select directly, or name to match/create. Ambiguous matching returns PROJECT_IDENTITY_AMBIGUOUS.
         */
        post: operations["post_projects_resolve_explicit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve project */
        get: operations["get_projects_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename/reclassify project with conflict detection */
        patch: operations["patch_projects_id"];
        trace?: never;
    };
    "/api/v1/projects/{id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source-linked deterministic resume/history context */
        get: operations["get_projects_id_context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read project policy */
        get: operations["get_projects_id_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update project policy */
        patch: operations["patch_projects_id_settings"];
        trace?: never;
    };
    "/api/v1/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deterministic filtered/full-text memory */
        get: operations["get_records"];
        put?: never;
        /**
         * Capture immutable memory
         * @description Optional Idempotency-Key is scoped to the authenticated credential. Identical retries return the saved capture; changed content under the same key conflicts.
         */
        post: operations["post_records"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Original capture plus metadata/revisions/relationships/evidence/audit */
        get: operations["get_records_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Audited metadata edit */
        patch: operations["patch_records_id_metadata"];
        trace?: never;
    };
    "/api/v1/records/{id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Audited amendment preserving original capture */
        post: operations["post_records_id_revisions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append evidence reference */
        post: operations["post_records_id_evidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}/mirror": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report local mirror outcome after central capture */
        post: operations["post_records_id_mirror"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deterministic full-text search */
        post: operations["post_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create source relationship */
        post: operations["post_relationships"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/relationships/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review relationship */
        post: operations["post_relationships_id_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/relationships/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review relationship */
        post: operations["post_relationships_id_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global normal-project defaults */
        get: operations["get_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Audited global defaults; stale writes conflict */
        patch: operations["patch_settings"];
        trace?: never;
    };
    "/api/v1/ai/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read optional provider settings; never plaintext key */
        get: operations["get_ai_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Configure optional provider */
        patch: operations["patch_ai_settings"];
        trace?: never;
    };
    "/api/v1/ai/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synthetic completion and embedding connectivity test */
        post: operations["post_ai_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect persisted jobs */
        get: operations["get_ai_jobs"];
        put?: never;
        /** Queue consent-filtered processing */
        post: operations["post_ai_jobs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Audited retry of failed job */
        post: operations["post_ai_jobs_id_retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve currently permitted derived artifacts */
        get: operations["get_suggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review derived artifact without altering raw history */
        post: operations["post_suggestions_id_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review derived artifact without altering raw history */
        post: operations["post_suggestions_id_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/semantic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optional indexed semantic similarity */
        post: operations["post_search_semantic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summaries/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue private source-cited Markdown document */
        post: operations["post_summaries_export"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Portable knowledge archive; excludes authentication/provider secrets/jobs/vectors */
        post: operations["post_export"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transactional native archive or legacy JSONL import */
        post: operations["post_import"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link or refresh public GitHub profile
         * @description Owner-authenticated operation. Uses optimistic profile versioning; public GitHub data cannot change authentication or credentials.
         */
        post: operations["link_github_profile"];
        /**
         * Unlink public GitHub profile
         * @description Owner-authenticated operation. Uses optimistic profile versioning; public GitHub data cannot change authentication or credentials.
         */
        delete: operations["unlink_github_profile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin browser-bound GitHub OAuth with PKCE
         * @description Expected Origin required. setup needs an initial single-use setupToken; recover needs a distinct administrator recovery setupToken. link requires an authenticated browser; replace requires browser authentication less than five minutes old. login requires an existing verified binding. The HttpOnly SameSite=Lax state cookie binds the single-use callback to this browser.
         */
        post: operations["post_auth_github_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consume GitHub OAuth code and browser-bound single-use state */
        get: operations["get_auth_github_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verified GitHub binding, complete cache freshness and key blocking status */
        get: operations["get_auth_github"];
        put?: never;
        post?: never;
        /**
         * Unlink GitHub using fresh independent local browser authentication
         * @description Authentication proof must be less than five minutes old. Invalidates GitHub-derived permissions and sessions, preserving independent local credentials and project knowledge. Administrator recovery can restore independent passkey access first.
         */
        delete: operations["delete_auth_github"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh the complete synchronized GitHub SSH key cache
         * @description Failed, incomplete or malformed responses preserve the previous complete snapshot and its age. Removed keys invalidate existing managed sessions. Late responses cannot overwrite a newer synchronization or replaced binding.
         */
        post: operations["post_auth_github_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Persistently block or explicitly unblock canonical SSH key material
         * @description Blocks take effect immediately across credentials carrying the same canonical key identity and survive restart, synchronization and removal/readdition. Unblocking does not restore previously invalidated sessions or stale eligibility.
         */
        post: operations["post_auth_github_block"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: string;
                message: string;
                details?: unknown;
            };
        };
        Entity: {
            id: string;
            version: number;
            /** Format: date-time */
            createdAt: string;
        };
        ProjectSettings: {
            enabledRecordTypes?: ("decision" | "adr" | "business_decision" | "finding" | "qa" | "failure" | "constraint" | "project_state")[];
            repoMirroring: {
                enabled: boolean;
                recordTypes: ("decision" | "adr" | "business_decision" | "finding" | "qa" | "failure" | "constraint" | "project_state")[];
            };
            crossProjectAnalysis: boolean;
            aiProcessing: boolean;
        };
        Project: components["schemas"]["Entity"] & {
            name?: string;
            /** @enum {string} */
            kind?: "normal" | "external";
            settings?: components["schemas"]["ProjectSettings"];
            sources?: {
                [key: string]: unknown;
            }[];
        };
        Capture: {
            /** @enum {string} */
            type: "decision" | "adr" | "business_decision" | "finding" | "qa" | "failure" | "constraint" | "project_state";
            title: string;
            /** @enum {string} */
            authority: "explicit" | "observed" | "inferred" | "derived" | "suggested";
            /** @enum {string} */
            confidence?: "high" | "medium" | "low" | "unknown";
            confidenceReason?: string;
            /** Format: date-time */
            happenedAt?: string;
            payload: {
                [key: string]: unknown;
            };
            actor?: {
                [key: string]: unknown;
            };
        };
        Record: components["schemas"]["Entity"] & {
            projectId?: string;
            /** @enum {string} */
            type?: "decision" | "adr" | "business_decision" | "finding" | "qa" | "failure" | "constraint" | "project_state";
            title?: string;
            content?: string;
            payload?: {
                [key: string]: unknown;
            };
            authority?: string | null;
            provenance?: {
                [key: string]: unknown;
            };
            gitContext?: {
                [key: string]: unknown;
            };
            recordedAt?: string;
            happenedAt?: string;
            actor?: {
                [key: string]: unknown;
            };
        };
        RevisionPrecondition: {
            expectedVersion?: number;
        };
        MetadataChanges: {
            displayTitle?: string;
            tags?: string[];
            archived?: boolean;
            curatedSummary?: string;
        };
        Scope: {
            projectId?: string;
            projectIds?: string[];
            /** @default false */
            crossProject: boolean;
        };
        AiSettings: {
            /** @default false */
            enabled: boolean;
            /** Format: uri */
            baseUrl?: string;
            model?: string;
            embeddingModel?: string;
            embeddingDimensions?: number;
            scheduleMinutes?: number;
            /** @default 600 */
            requestTimeoutSeconds: number;
            /** @enum {string} */
            reasoningEffort?: "default" | "none" | "low" | "medium" | "high" | "xhigh";
            similarityThreshold?: number;
            analysisModes?: ("summary" | "classification" | "duplicate_candidate" | "relationship_candidate" | "contradiction" | "cluster" | "pattern" | "recommendation" | "export")[];
            apiKeyConfigured?: boolean;
            version?: number;
            /** @default 4096 */
            maxOutputTokens: number;
        };
        AiSettingsPatch: {
            expectedVersion?: number;
            enabled?: boolean;
            /** Format: uri */
            baseUrl?: string;
            model?: string;
            embeddingModel?: string;
            embeddingDimensions?: number;
            scheduleMinutes?: number;
            requestTimeoutSeconds?: number;
            /** @enum {string} */
            reasoningEffort?: "default" | "none" | "low" | "medium" | "high" | "xhigh";
            similarityThreshold?: number;
            analysisModes?: ("summary" | "classification" | "duplicate_candidate" | "relationship_candidate" | "contradiction" | "cluster" | "pattern" | "recommendation" | "export")[];
            /** @description Omit to preserve the stored key; empty string removes it. */
            apiKey?: string;
            /** @default 4096 */
            maxOutputTokens: number;
        };
        JobRequest: components["schemas"]["Scope"] & {
            /** @enum {string} */
            type: "analyze" | "embed" | "export";
            /** @enum {string} */
            format?: "handoff" | "architecture" | "decisions" | "client_history" | "adr";
        };
        Job: components["schemas"]["Entity"] & {
            /** @enum {string} */
            type?: "analyze" | "embed" | "export";
            /** @enum {string} */
            status?: "queued" | "running" | "completed" | "failed";
            scope?: components["schemas"]["Scope"];
            /** @enum {string} */
            format?: "handoff" | "architecture" | "decisions" | "client_history" | "adr";
            attempts?: number;
            runAfter?: string;
            leaseUntil?: string | null;
            lastError?: string | null;
            artifactIds?: string[];
            /** @description Audited suggestions omitted for insufficient evidence; valid siblings remain available. */
            warnings?: {
                /** @enum {string} */
                code: "AI_INSUFFICIENT_EVIDENCE";
                kind: string;
                count: number;
            }[];
        };
        Artifact: components["schemas"]["Entity"] & {
            /** @enum {string} */
            kind?: "summary" | "classification" | "duplicate_candidate" | "relationship_candidate" | "contradiction" | "cluster" | "pattern" | "recommendation" | "export";
            title?: string;
            /** @enum {string} */
            status?: "pending" | "accepted" | "rejected";
            content?: {
                text?: string;
                markdown?: string;
                fromRecordId?: string;
                toRecordId?: string;
                relationshipType?: string;
                tags?: string[];
                classification?: string;
            };
            sourceRecordIds?: string[];
            projectIds?: string[];
            crossProject?: boolean;
            /** @enum {string} */
            authority?: "derived";
            generator?: {
                [key: string]: unknown;
            };
            generatedAt?: string;
            /** @enum {string} */
            format?: "handoff" | "architecture" | "decisions" | "client_history" | "adr";
        };
        SemanticQuery: components["schemas"]["Scope"] & {
            query: string;
            /** @default 20 */
            limit: number;
        };
        NativeArchive: {
            /** @enum {string} */
            format: "scratchpad";
            /** @constant */
            version: 1;
            exportedAt?: string;
            data: {
                [key: string]: unknown;
            };
        };
        LegacyImport: {
            /** @enum {string} */
            format: "jsonl";
            projectId: string;
            /** @description JSONL text capped at 32 MiB. */
            jsonl: string;
            source?: {
                filename?: string;
            };
            sourceName?: string;
        };
        /** @description Public GitHub profile snapshot; not an authenticated identity. */
        GithubProfile: {
            username: string;
            displayName: string | null;
            /** Format: uri */
            avatarUrl: string | null;
            /** Format: uri */
            profileUrl: string;
            /** Format: date-time */
            fetchedAt: string;
        };
        OwnerProfile: {
            id: string;
            displayName: string;
            version: number;
            github?: components["schemas"]["GithubProfile"] | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Stable JSON error envelope. Common codes: AUTH_REQUIRED, AUTH_INVALID, AUTH_CHALLENGE_EXPIRED, AUTH_CHALLENGE_USED, VALIDATION_FAILED, CONFLICT, PROJECT_NOT_FOUND, PROJECT_IDENTITY_REQUIRED, PROJECT_IDENTITY_AMBIGUOUS, AI_DISABLED, AI_NOT_ALLOWED, AI_UNAVAILABLE, AI_SCOPE_TOO_LARGE, DATABASE_NOT_READY. Additional codes may be introduced. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "ok";
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "ready";
                        /** @enum {string} */
                        database?: "sqlite" | "postgres";
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_auth_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        initialized?: boolean;
                        authenticated?: boolean;
                        githubConfigured?: boolean;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_auth_mcp_challenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    publicKey: string;
                    label?: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        challengeId?: string;
                        nonce?: string;
                        namespace?: string;
                        expiresAt?: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_auth_mcp_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    challengeId: string;
                    publicKey: string;
                    signature: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken?: string;
                        /** Format: date-time */
                        expiresAt?: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_auth_credentials_challenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    publicKey: string;
                    label?: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        challengeId?: string;
                        nonce?: string;
                        namespace?: string;
                        expiresAt?: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_auth_credentials_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    challengeId: string;
                    publicKey: string;
                    signature: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        credentialId?: string;
                        fingerprint?: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_auth_register_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    setupToken?: string;
                    label?: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        challengeId?: string;
                        options?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_auth_register_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    challengeId: string;
                    response: {
                        [key: string]: unknown;
                    };
                    setupToken?: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        authenticated?: boolean;
                        expiresAt?: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_auth_login_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        challengeId?: string;
                        options?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_auth_login_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    challengeId: string;
                    response: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        authenticated?: boolean;
                        expiresAt?: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        authenticated?: boolean;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_auth_credentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        credentials?: ({
                            /** @enum {string} */
                            source?: "local" | "github";
                            /** @enum {string} */
                            kind?: "webauthn" | "ssh" | "github";
                        } & {
                            [key: string]: unknown;
                        })[];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    delete_auth_credentials_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revoked?: boolean;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profile?: components["schemas"]["OwnerProfile"];
                        database?: {
                            /** @enum {string} */
                            engine?: "sqlite" | "postgresql";
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patch_profile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Alternative optimistic version precondition where supported; profile PATCH requires body expectedVersion. */
                "If-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName: string;
                    expectedVersion: number;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profile?: components["schemas"]["OwnerProfile"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        projects?: components["schemas"]["Project"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_projects_resolve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    context: {
                        git: {
                            remote: string;
                            branch?: string;
                            commit?: string;
                        };
                    };
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        project?: components["schemas"]["Project"];
                        resolution?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_projects_resolve_explicit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** @enum {string} */
                    kind?: "normal" | "external";
                    projectId?: string;
                    context?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        project?: components["schemas"]["Project"];
                        resolution?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_projects_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        project?: components["schemas"]["Project"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patch_projects_id: {
        parameters: {
            query?: never;
            header?: {
                /** @description Alternative optimistic version precondition where supported; profile PATCH requires body expectedVersion. */
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** @enum {string} */
                    kind?: "normal" | "external";
                    expectedVersion?: number;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        project?: components["schemas"]["Project"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_projects_id_context: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_projects_id_settings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        settings?: components["schemas"]["ProjectSettings"];
                        version?: number;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patch_projects_id_settings: {
        parameters: {
            query?: never;
            header?: {
                /** @description Alternative optimistic version precondition where supported; profile PATCH requires body expectedVersion. */
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    settings: components["schemas"]["ProjectSettings"];
                    expectedVersion?: number;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        settings?: components["schemas"]["ProjectSettings"];
                        version?: number;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_records: {
        parameters: {
            query?: {
                /** @description Optional filter. */
                projectId?: string;
                /** @description Repeated query values allowed. */
                projectIds?: string[];
                /** @description Optional filter. */
                type?: string;
                /** @description Repeated query values allowed. */
                types?: string[];
                /** @description Optional filter. */
                tag?: string;
                /** @description Optional filter. */
                q?: string;
                /** @description Optional filter. */
                from?: string;
                /** @description Optional filter. */
                to?: string;
                /** @description Optional filter. */
                branch?: string;
                /** @description Optional filter. */
                authority?: string;
                /** @description Optional filter. */
                confidence?: string;
                /** @description Optional filter. */
                status?: string;
                /** @description Optional filter. */
                relatedTo?: string;
                /** @description Optional filter. */
                relationshipType?: string;
                /** @description Optional filter. */
                source?: string;
                /** @description Optional filter. */
                gitPath?: string;
                /** @description Optional filter. */
                archived?: boolean;
                /** @description Optional filter. */
                limit?: number;
                /** @description Optional filter. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        records?: components["schemas"]["Record"][];
                        nextCursor?: string | null;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_records: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    projectId: string;
                    record: components["schemas"]["Capture"];
                    gitContext?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Successful response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        record?: components["schemas"]["Record"];
                        mirror?: {
                            eligible?: boolean;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_records_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        record?: components["schemas"]["Record"];
                        metadata?: {
                            [key: string]: unknown;
                        };
                        revisions?: {
                            [key: string]: unknown;
                        }[];
                        relationships?: {
                            [key: string]: unknown;
                        }[];
                        evidence?: {
                            [key: string]: unknown;
                        }[];
                        mirror?: {
                            [key: string]: unknown;
                        };
                        audit?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patch_records_id_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetadataChanges"] & components["schemas"]["RevisionPrecondition"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        metadata?: {
                            [key: string]: unknown;
                        };
                        revision?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_records_id_revisions: {
        parameters: {
            query?: never;
            header?: {
                /** @description Alternative optimistic version precondition where supported; profile PATCH requires body expectedVersion. */
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    changes: components["schemas"]["MetadataChanges"];
                    reason?: string;
                    expectedVersion?: number;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        metadata?: {
                            [key: string]: unknown;
                        };
                        revision?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_records_id_evidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "url" | "git_commit" | "pull_request" | "issue" | "file" | "conversation" | "test" | "deployment" | "other";
                    reference: string;
                    revision?: string;
                    description?: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        evidence?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_records_id_mirror: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    attempted: boolean;
                    succeeded: boolean;
                    path?: string;
                    error?: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        mirror?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query?: string;
                    projectIds?: string[];
                    types?: string[];
                    limit?: number;
                    cursor?: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        records?: components["schemas"]["Record"][];
                        nextCursor?: string | null;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_relationships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    fromRecordId: string;
                    toRecordId: string;
                    /** @enum {string} */
                    type: "related_to" | "supports" | "contradicts" | "refines" | "replaces" | "partially_replaces" | "depends_on" | "implements" | "caused_by" | "answers";
                    /** @enum {string} */
                    authority?: "explicit" | "inferred" | "suggested";
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        relationship?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_relationships_id_accept: {
        parameters: {
            query?: never;
            header?: {
                /** @description Alternative optimistic version precondition where supported; profile PATCH requires body expectedVersion. */
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionPrecondition"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        relationship?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_relationships_id_reject: {
        parameters: {
            query?: never;
            header?: {
                /** @description Alternative optimistic version precondition where supported; profile PATCH requires body expectedVersion. */
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionPrecondition"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        relationship?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        settings?: {
                            id?: string;
                            version?: number;
                            aiEnabled?: boolean;
                            defaultProjectSettings?: components["schemas"]["ProjectSettings"];
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patch_settings: {
        parameters: {
            query?: never;
            header?: {
                /** @description Alternative optimistic version precondition where supported; profile PATCH requires body expectedVersion. */
                "If-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    settings: {
                        aiEnabled?: boolean;
                        defaultProjectSettings?: components["schemas"]["ProjectSettings"];
                    };
                    expectedVersion?: number;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        settings?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_ai_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSettings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patch_ai_settings: {
        parameters: {
            query?: never;
            header?: {
                /** @description Alternative optimistic version precondition where supported; profile PATCH requires body expectedVersion. */
                "If-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiSettingsPatch"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSettings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_ai_test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        model?: string;
                        embeddingModel?: string;
                        dimensions?: number;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_ai_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        jobs?: components["schemas"]["Job"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_ai_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job?: components["schemas"]["Job"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_ai_jobs_id_retry: {
        parameters: {
            query?: never;
            header?: {
                /** @description Alternative optimistic version precondition where supported; profile PATCH requires body expectedVersion. */
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionPrecondition"];
            };
        };
        responses: {
            /** @description Successful response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job?: components["schemas"]["Job"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_suggestions: {
        parameters: {
            query?: {
                /** @description Optional filter. */
                projectId?: string;
                /** @description Repeated query values allowed. */
                projectIds?: string[];
                /** @description Optional filter. */
                crossProject?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        suggestions?: components["schemas"]["Artifact"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_suggestions_id_accept: {
        parameters: {
            query?: never;
            header?: {
                /** @description Alternative optimistic version precondition where supported; profile PATCH requires body expectedVersion. */
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionPrecondition"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        suggestion?: components["schemas"]["Artifact"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_suggestions_id_reject: {
        parameters: {
            query?: never;
            header?: {
                /** @description Alternative optimistic version precondition where supported; profile PATCH requires body expectedVersion. */
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionPrecondition"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        suggestion?: components["schemas"]["Artifact"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_search_semantic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemanticQuery"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results?: {
                            record?: components["schemas"]["Record"];
                            score?: number;
                        }[];
                        model?: string;
                        indexRequired?: boolean;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_summaries_export: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    projectId: string;
                    /** @enum {string} */
                    format: "handoff" | "architecture" | "decisions" | "client_history" | "adr";
                };
            };
        };
        responses: {
            /** @description Successful response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job?: components["schemas"]["Job"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_export: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeArchive"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_import: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativeArchive"] | components["schemas"]["LegacyImport"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        imported?: number;
                        skipped?: number;
                        warnings?: {
                            [key: string]: unknown;
                        }[];
                        records?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    link_github_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                    username: string;
                };
            };
        };
        responses: {
            /** @description Updated owner profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profile: components["schemas"]["OwnerProfile"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    unlink_github_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                };
            };
        };
        responses: {
            /** @description Updated owner profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profile: components["schemas"]["OwnerProfile"];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_auth_github_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    intent: "setup" | "login" | "link" | "replace" | "recover";
                    setupToken?: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        authorizationUrl: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    get_auth_github_callback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Establishes browser session and redirects to the dashboard; sets HttpOnly session cookie and clears state cookie */
            302: {
                headers: {
                    Location?: string;
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed authorization redirects to the dashboard with authError set to a fixed safe error code; no upstream message, token or private data is exposed. */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    get_auth_github: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        configured: boolean;
                        binding: {
                            accountId: string;
                            username: string;
                        } | null;
                        /** Format: date-time */
                        lastSuccessfulSyncAt: string | null;
                        /** Format: date-time */
                        cacheExpiresAt: string | null;
                        cacheValid: boolean;
                        lastSyncError: string | null;
                        keys: {
                            publicKey: string;
                            fingerprint: string;
                            categories: ("authentication" | "signing")[];
                            blocked: boolean;
                        }[];
                        freshAuthenticationRequired: boolean;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    delete_auth_github: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        unlinked: true;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_auth_github_sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        configured: boolean;
                        binding: {
                            accountId: string;
                            username: string;
                        } | null;
                        /** Format: date-time */
                        lastSuccessfulSyncAt: string | null;
                        /** Format: date-time */
                        cacheExpiresAt: string | null;
                        cacheValid: boolean;
                        lastSyncError: string | null;
                        keys: {
                            publicKey: string;
                            fingerprint: string;
                            categories: ("authentication" | "signing")[];
                            blocked: boolean;
                        }[];
                        freshAuthenticationRequired: boolean;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    post_auth_github_block: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    publicKey: string;
                    blocked: boolean;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        configured: boolean;
                        binding: {
                            accountId: string;
                            username: string;
                        } | null;
                        /** Format: date-time */
                        lastSuccessfulSyncAt: string | null;
                        /** Format: date-time */
                        cacheExpiresAt: string | null;
                        cacheValid: boolean;
                        lastSyncError: string | null;
                        keys: {
                            publicKey: string;
                            fingerprint: string;
                            categories: ("authentication" | "signing")[];
                            blocked: boolean;
                        }[];
                        freshAuthenticationRequired: boolean;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
