import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, {
  astToString,
} from "../packages/clients/generator/index.mjs";

const root = resolve(import.meta.dirname, "..");
const checking = process.argv.includes("--check");
const temp = mkdtempSync(join(tmpdir(), "scratchpad-clients-"));
try {
  const source = new URL("../docs/openapi.json", import.meta.url);
  const ts = `// Generated by openapi-typescript 7.13.0. Do not edit.\n${astToString(await openapiTS(source))}`;
  const go = resolve(root, "packages/clients/go");
  const target = join(temp, "generated.go");
  execFileSync(
    "go",
    [
      "run",
      "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.8.0",
      "--config",
      "config.yaml",
      "-o",
      target,
      fileURLToPath(source),
    ],
    { cwd: go, stdio: "inherit" },
  );
  for (const [path, content] of [
    ["packages/clients/typescript/schema.ts", ts],
    ["packages/clients/go/generated.go", readFileSync(target, "utf8")],
  ]) {
    if (checking) {
      if (readFileSync(resolve(root, path), "utf8") !== content)
        throw new Error(`${path} is stale; run npm run sdk:generate`);
    } else writeFileSync(resolve(root, path), content);
  }
} finally {
  rmSync(temp, { recursive: true, force: true });
}
